### ISSUE TITLE
[PE-D][Tester A] addVisit able to add records with dates in the future.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-2/tp#320]
![Screenshot 2024-11-08 at 4.56.47 PM.png](https://raw.githubusercontent.com/ChuaCleon/ped/main/files/b5669112-502a-4266-b6a2-b4070cd3a803.png)

Should the addVisit functionality only be for past visits? Able to add visit records for the future which feels like it should fall under addAppointment. I.e. future visits should fall under appointments, and it should not be able to have a diagnosis yet.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ChuaCleon/ped#3

**Comment by kaboomzxc** [comment]
if i try to stand in the shoes or think from the perspective of a real, earnest, serious clinician user, 
i do not think a serious clinician will key in a future fake visit with imagined diagnoses and medications. 

in addition, we have "editVisit" command if the clinician needs to correct a entry.

**Comment by kaboomzxc** [comment]
update 1 :
furthermore to add. 

from a user perspective, it may not feel so good to use a product with so much restriction.

imagine two cases :
1. the program checks by the current second, and prohibits user entirely to enter in slightly future date and time. 
it may feel "this damn program doesn't let me press enter !!"

compare with 
2. program allows user to key in an entry. with a option to edit as and when is needed. 
this feels more satisfactory 

which one would you feel nicer and prefer?

**Comment by kaboomzxc** [comment]
Update :  i implemented this in the end. Thank you so much for the helpful feedback.
